### ISSUE TITLE
MVC 모델이란 무엇일까?

### ISSUE THREAD

**Issue by hhjung1202** [polmki123/SONMAT_WEB#13]
멘토 형님께 탈탈 털리고 써봅니다.

기존에 생각했던 MVC모델은
![image](https://user-images.githubusercontent.com/17779678/47337002-ee086480-d6cc-11e8-82dd-4f77cfb0d5a9.png)
M : DB를 위한 데이터 형태를 잡고 이를 손쉽게 읽고 저장하기 위한 틀을 만든다.
![image](https://user-images.githubusercontent.com/17779678/47337043-2ad45b80-d6cd-11e8-9ef7-844b37f02ecb.png)
V : DB를 Query하여 원하는 정보를 사용자에게 보여준다.
![image](https://user-images.githubusercontent.com/17779678/47337065-4d667480-d6cd-11e8-95fc-40417d20b552.png)
C : 사용자나 시스템의 요청을 처리하여 DB에 Create, Update, Delete 를 한다.

이거 였는데, 형님이 말씀하신 MVC가 나온 이유를 생각해보기 위해서는
과거 웹을 개발할 때로 돌아가봐야 한다며 예시 든 코드가 아래와 갔다.
`<span> {% java.getXXX(); System.out.println(javaInstance.getXXX(); }</span>`
이 코드를 보면 HTML 코드, JAVASCRIPT 코드가 혼용되어 있고, get함수를 통해서 외부 DB로부터 Query해온 데이터를 가져오는 듯한 코드가 한 줄에 혼용되어 있다. 
이런식으로 코드를 작성하게 되면 코드 중복성도 많아지고 코드가 더러워진다.
코드가 더러워지게 되면 더러워질수록 분업을 할 수 없는 코드로 변해간다.
(오로지 1인만을 위한 개발 프로젝트 같이)

그렇기에 아래 그림과 같이 나도 웹을 구현할 때 자연스레 Model 부분과, View(HTML, CSS, JS) 부분과, Control(routes에서 url에 따른 서버 요청 처리)를 나누어 구현한다
![image](https://user-images.githubusercontent.com/17779678/47337278-3bd19c80-d6ce-11e8-9403-2ec8a76bc6a8.png)

**Comment by sjKang01401** [comment]
제가 이전에 했던 프로젝트로 보여드리면

![2018-10-23 18 15 41](https://user-images.githubusercontent.com/26760226/47350009-cf679500-d6ef-11e8-8792-97f5e7eefecb.PNG)

이런식으로 구성이 되어있는데
Controller -> Service -> ServiceImpl -> Dao -> DaoImpl -> mapper.xml  순으로
1. Front에서의 request url에 따라 Controller로 들어가고
2. 해당 컨트롤러에서 사용될 비즈니스 로직이 있는 서비스를 불러옵니다.
-----------------------------------------------------------------------여기까지가 제가 생각했던 Control 이고
3. ServiceImpl 내부에서 DB에 접근해야할 때 Dao 함수를 호출해주고
4. MyBatis를 사용했었기 때문에 Dao에서는 xml 파일에 저장되어있는 SQL과 연결해주었습니다.
+) SQL의 결과로 받아올 객체에 대해서는 dto 패키지로 정리하였습니다.
-----------------------------------------------------------------------여기까지가 제가 생각한 Model 입니다.


제가 인턴에서 했던 프로젝트에서는 nodejs를 사용한 프론트 쪽 프로젝트가 따로 있고
프론트에서 호출할 api를 구현하는 서버 프로젝트가 따로 있었는데
그래서 response의 형태가 항상 json과 같은 데이터였지, view였던 적이 없었습니다.

그래서 어제 MVC 실제 사용한 것에 대해 답변드리려고 보니까
제가 작업했던 부분에 대해 어떻게 view를 설명해야할지 모르겠습니다...
( 3Tier 쪽도 비슷한 이유로 제 안에서 정리가 잘 안되어있는데.. 이건 시험끝나고 다시 정리하면서 여쭤보겠습니다..^^;;)

**Comment by polmki123** [comment]
제가 생각한 MVC 모델은
제가 예전에 잠깐 만들었던 django 프로젝트에선 
![model](https://user-images.githubusercontent.com/28795477/47353035-312afd80-d6f6-11e8-92a8-81be368b3b8e.png)
M : 사용자의 요청을 받아들이 활용하는데 쓰이는 데이터 DB 모델을 만들고
![controller](https://user-images.githubusercontent.com/28795477/47353527-726fdd00-d6f7-11e8-8551-919994ae5512.png)
C : 사용자 요청에 따른 처리 프로세스를 구현
![view](https://user-images.githubusercontent.com/28795477/47353112-6f282180-d6f6-11e8-968b-9a85ff9f3595.png)
![url](https://user-images.githubusercontent.com/28795477/47353383-1b6a0800-d6f7-11e8-8d81-2c2edea4debf.png)
V : 사용자 요청에 따른 응답을 보여주는 템플릿 과 url

이렇게 구현했습니다. 
![default](https://user-images.githubusercontent.com/28795477/47353224-ae567280-d6f6-11e8-90f5-d1b08d5fc44d.png)
django가 기본적으로 mvc를 기반으로 만들어진 프레임워크라 그런지 모델 ,템플릿, 컨트롤이 세부분이 명확하게 나누어 져있어 사용하기 편했습니다. 근데 이건 django를 기반으로 말씀드리는 부분이라 틀린 것일 수도 있겠지만 제가 공부했던 결과는 이정도 입니다.
