### ISSUE TITLE
naver cloud platform 에 계정을 생성한다.

### ISSUE THREAD

**Issue by headcha** [polmki123/SONMAT_WEB#3]
1. naver cloud platform 에 계정을 생성한다. 
2. 계정 생성후 300,000 크레딧을 받기 위해 결제 카드를 등록한다.

티켓 종료 조건.

300,000 크레딧을 부여 받은 후 티켓을 종료 한다.

**Comment by hhjung1202** [comment]
네이버 클라우드 플랫폼 계정
ID : okok6403@naver.com
PW : @thsakt123
