### ISSUE TITLE
mysql 용 server image 를 생성한다.

### ISSUE THREAD

**Issue by headcha** [polmki123/SONMAT_WEB#4]
1. 서버 이미지는 알아서 선택. ( centos 추천 ) 
2. 용량과 사양은 적당히 ( 월 1~2만원 정도 ) 
3. 서버 계정은 root / Thsakt!@#123 ( 손맛!@#123 ) 으로 설정.
4. 방화벽 룰 
  - 3306 port 는 외부에서 접근 허용한다. (database 접근용 ) 
  - 22 port 는 외부에서 접근 허용한다. ( 서버 관리용 ) 
티켓 종료 조건.
- 리눅스 서버 설치후 IP 를 댓글로 등록한다.
- 댓글로 등록한 IP 로 서버에 접근 할 수 있어야 한다. ssh root@IP / password

**Comment by hhjung1202** [comment]
OS : CentOS 6.6
Server IP : 45.119.144.116
SSH Connection : port 1027
Server 계정 : root / Thsakt!@#123 (손맛!)
User 계정 : sonmat / sonmat
방화벽 툴 iptables

**Comment by polmki123** [comment]
public Ip: 210.89.188.101
port : 3306
