### ISSUE TITLE
node.js 를 설치한다.

### ISSUE THREAD

**Issue by headcha** [polmki123/SONMAT_WEB#7]
1. 버전은 알아서 ( 최신 안정 버전 ) 
2. 설치 계정도 알아서 ( 보안상 application 계정설치를 권장하나 학습용 임으로 root 로 설치해도 무방 )
3. 설치후 설치 정보를 댓글로 공유한다.
4. port 는 9000을 이용한다.

티켓 종료 조건.
외부에서 http://serverip:9000 으로 접근해 index page 에 접근할 수 있다.

**Comment by hhjung1202** [comment]
Nodejs 8.12.0 LTS 버전 다운로드 완료
설치 계정 root
npm 버전 6.4.1
![image](https://user-images.githubusercontent.com/17779678/47383277-56902980-d73f-11e8-8540-990fc92294a5.png)

접근 완료
